name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install toolchain
      run: sudo apt-get install -y lcov

    - name: Configure CMake
      run: cmake --preset default-configure-coverage

    - name: Build
      run: cmake --build --preset default-build-coverage

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest

    - name: Collect coverage
      working-directory: ${{github.workspace}}/build
      run: |
        lcov --capture --directory testbin/ --include "${{github.workspace}}/sparsematrix/sparsematrix.h" --output-file coverage.info
        coverage=$( lcov --list coverage.info | grep -e '^sparsematrix.h' | awk -F'[[:space:]]+' '{gsub(/[^[:digit:]\.]/, "", $2); print $2}' )
        exit $( echo "$coverage > $min_coverage" | bc -l )
      env:
        min_coverage: 90
